apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-webhook-server
  template:
    metadata:
      labels:
        app: alertmanager-webhook-server
    spec:
      containers:
      - name: alertmanager-webhook-server
        image: quay.io/cloud-for-you/alertmanager-webhook-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi