apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-server
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: alertmanager-webhook-server
  type: ClusterIP