apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-server
spec:
  template:
    spec:
      containers:
      - name: alertmanager-webhook-server
        image: quay.io/cloud-for-you/alertmanager-webhook-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "development"
        - name: RECEIVER_NAME
          value: "kafka"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "alerts"
        - name: KAFKA_CLIENT_CERT
          value: "/cert/tls.crt"
        - name: KAFKA_CLIENT_KEY
          value: "/cert/tls.key"
        - name: KAFKA_CA_CERT 
          value: "/cert/ca.crt"
        volumeMounts:
        - name: certs
          mountPath: /cert
      volumes:
      - name: certs
        secret:
          secretName: kafka-client-tls
